### ISSUE TITLE
requirements.txt 

### ISSUE THREAD

**Issue by Huang-Tzu-Heng** [OliverHxh/SkeletonGCL#1]
Hello, I did not find requirements.txt

**Comment by carpenterChina** [comment]
没有这个文件，也可以直接运行，看少什么就install什么。不过你最后会因为没有NTU120_CSub.npz文件而失败！这个项目并不友好，它借鉴了其他另外几个项目的数据处理代码，但是这里没有给出，所以还得去其他地方copy再改路径，挺麻烦的！

**Comment by carpenterChina** [comment]
> Hello, I did not find requirements.txt
没有这个文件，也可以直接运行，看少什么就install什么。不过你最后会因为没有NTU120_CSub.npz文件而失败！这个项目并不友好，它借鉴了其他另外几个项目的数据处理代码，但是这里没有给出，所以还得去其他地方copy再改路径，挺麻烦的！

**Comment by OliverHxh** [comment]
Hi, sorry for the late reply. I have included the requirements.txt file in the repository. Please check it.
