### ISSUE TITLE
contrastive loss

### ISSUE THREAD

**Issue by Brian417-cup** [OliverHxh/SkeletonGCL#2]
Hello, I discover in your paper, there lies a Instance-level memory bank and semantic-level memory bank. However, when I look through your source code, I have some confusion:
1. mem_size in the train code have directly set to [the len of dataset](https://github.com/OliverHxh/SkeletonGCL/blob/main/main.py#L284-#L287) , but in paper, this is a hyper-parameter .
2. [The memory bank in InfoNCEGraph](https://github.com/OliverHxh/SkeletonGCL/blob/main/model/loss.py#L18-#L20) can I understand is just the Instance-Level memory bank ? But where is the source code about Semenatic-Level Memory Bank and its momentum update strategy?

I know asking so many questions at once can be quite troublesome for you, but I still look forward to your clear answer. Thank you very much!

**Comment by OliverHxh** [comment]
Dear Brian, 

After the acceptance, we improved our code in these two aspects where we eliminate the hyper-parameter and Semenatic-Level Memory Bank. And it can still achieve similar results. 

Since the camera-ready version cannot be changed, we had not updated our paper accordingly.
