### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by xinywang1** [OliverHxh/SkeletonGCL#6]
Hello, thank you very much for your work! But I have a question. When I want to use InfoNCEGraph to train features, the error "one of the variables needed for gradient computation has been modified by an in-place operation" appears. However, when I modify line 39 of "class InfoNCEGraph" to "all pairs=einsum ('n c, m c ->n m ', fn formed. detach(), self. Bank)", the code runs normally. Why does this error occur? Will my modifications like this affect the comparison training effect? 
Thank you very much for your response!

**Comment by OliverHxh** [comment]
Sorry, I do not know how this issue happens. But if you detach the feature ``f_normed`` in the 39 line, the contrastive loss will not backward to the previous layers, which cannot function as we want.
